/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118050-ga518b5540d-20241212"
#endif /* AVUTIL_FFVERSION_H */
